version: '2'

services:
  api:
    build: .
    environment:
      - SPARK_MASTER_URL=spark://spark:7077
    ports:
    - '8080:8080'
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ${PWD}/data:/data/db
